FROM node:18

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

USER root
COPY back/ /home/node/app
WORKDIR /home/node/app
RUN rm -rf node_modules package-lock.json build && chown -R node:node /home/node/app
USER node

RUN npm install

CMD npm run migrate && npm run dev
