FROM node:18

USER root
COPY front/ /home/node/app
WORKDIR /home/node/app
RUN rm -rf node_modules package-lock.json && chown -R node:node /home/node/app
USER node

RUN npm install

CMD [ "npm", "run", "dev" ]
