version: "3.0"
services:
  db:
    image: postgres
    container_name: rldb-postgres
    restart: always
    ports:
      - 5432:5432
    env_file: [ .env ]
    networks:
      netdev:
        ipv4_address: 10.10.0.4

  front:
    restart: always
    env_file: [ .env ]
    ports:
      - "7080:80"
      - "5173:5173"
    build:
      context: .
      dockerfile: prod/Dockerfile_front

  node:
    restart: always
    depends_on:
      - db
    env_file: [ .env ]
    build:
      context: .
      dockerfile: prod/Dockerfile_back
    ports:
      - "3003:3003"
    volumes:
      - ./back/src:/home/node/app/src

networks:
  netdev:
    name: netdev
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24

volumes:
  pgdata:
