name: donation-timer
services:
  pro-front:
    restart: always
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - VITE_CLIENT_ID=${VITE_CLIENT_ID}
      - VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL}
      - VITE_REDIRECT_URL=${VITE_REDIRECT_URL}
      - VITE_BASE_URL=${VITE_BASE_URL}
    build:
      context: ..
      dockerfile: docker/Dockerfile-pro-front
    ports:
      - "3080:3080"
  pro-back:
    restart: always
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
    build:
      context: ..
      dockerfile: docker/Dockerfile-pro-back
    ports:
      - "3003:3003"
    networks:
      - backnet
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    restart: always
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - backnet
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
networks:
  backnet:
    driver: bridge
volumes:
  pgdata:
