#!/bin/bash
# Installs/refreshes the donationtimer watchdog (systemd user units). Idempotent — update.sh runs
# this on every deploy so the server always matches the repo. Safe to rerun by hand any time.
#
# What it sets up:
#  - donationtimer-watchdog.timer/.service: probes the app every minute, restarts the stack if down
#  - a Restart=on-failure drop-in for the donationtimer unit (skipped for oneshot units, where
#    systemd forbids it — the watchdog's failed-state recovery covers those)
#  - login lingering, so the user units keep running after logout/reboot
set -e
cd "$(dirname "$0")"
REPO_SYSTEMD_DIR="$(pwd)"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
mkdir -p "$UNIT_DIR"

# generated (not copied) so ExecStart points at this checkout wherever it lives
cat > "$UNIT_DIR/donationtimer-watchdog.service" <<EOF
# Generated by donation-timer/systemd/install-watchdog.sh — edit the repo copy, not this file.
[Unit]
Description=Donation Timer watchdog — restarts the stack if the app stops answering

[Service]
Type=oneshot
ExecStart=$REPO_SYSTEMD_DIR/donationtimer-watchdog.sh
EOF

cp donationtimer-watchdog.timer "$UNIT_DIR/donationtimer-watchdog.timer"

# let systemd itself revive the stack if the compose process dies (first line of defense; the
# watchdog is the second, for wedged-but-running states). Restart= is illegal on oneshot units.
unit_type=$(systemctl --user show donationtimer -p Type --value 2>/dev/null || true)
if [ -n "$unit_type" ] && [ "$unit_type" != "oneshot" ]; then
    mkdir -p "$UNIT_DIR/donationtimer.service.d"
    cat > "$UNIT_DIR/donationtimer.service.d/watchdog-restart.conf" <<EOF
# Generated by donation-timer/systemd/install-watchdog.sh
[Service]
Restart=on-failure
RestartSec=10
EOF
else
    echo "note: donationtimer unit is '$unit_type' — skipping the Restart= drop-in (watchdog still covers it)"
fi

systemctl --user daemon-reload
systemctl --user enable --now donationtimer-watchdog.timer

# user units only run while a session exists unless lingering is on — required to survive reboots
if ! loginctl enable-linger "$USER" 2>/dev/null; then
    echo "note: couldn't enable lingering; run once as root: loginctl enable-linger $USER"
fi

echo "Watchdog installed. Next check: $(systemctl --user show donationtimer-watchdog.timer -p NextElapseUSecRealtime --value)"
echo "Watch it work with: journalctl --user -u donationtimer-watchdog -f"
