FROM node:18-alpine as build-stage

USER root
COPY front/ /home/node/app
COPY .env /home/node/app/.env
WORKDIR /home/node/app
RUN rm -rf node_modules package-lock.json && chown -R node:node /home/node/app
USER node

RUN npm install && npm run build

FROM nginx:1.15

COPY --from=build-stage /home/node/app/dist/ /usr/share/nginx/html
COPY ./prod/nginx.conf /etc/nginx/nginx.conf
COPY ./prod/timer.crt /etc/ssl/timer.crt
COPY ./prod/timer.key /etc/ssl/private/timer.key

RUN rm /etc/nginx/conf.d/default.conf
